### ISSUE TITLE
Crash at create a new world

### ISSUE THREAD

**Issue by magcicada** [TeamMoegMC/SteamPowered#5]
Crash at create a new world at version 1.1.3,this is the CR:

Description: mouseClicked event handler

java.lang.IllegalStateException: failed to create a child event loop
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:88) ~[netty-all-4.1.25.Final.jar:4.1.25.Final] {}
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:58) ~[netty-all-4.1.25.Final.jar:4.1.25.Final] {}
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:47) ~[netty-all-4.1.25.Final.jar:4.1.25.Final] {}
	at io.netty.channel.MultithreadEventLoopGroup.<init>(MultithreadEventLoopGroup.java:59) ~[netty-all-4.1.25.Final.jar:4.1.25.Final] {}
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:77) ~[netty-all-4.1.25.Final.jar:4.1.25.Final] {}
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:72) ~[netty-all-4.1.25.Final.jar:4.1.25.Final] {}
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:59) ~[netty-all-4.1.25.Final.jar:4.1.25.Final] {}
	at net.minecraft.network.NetworkSystem.func_201135_f(NetworkSystem.java:46) ~[?:?] {re:classloading}
	at net.minecraft.util.LazyValue.func_179281_c(SourceFile:16) ~[?:?] {re:classloading}
	at net.minecraft.network.NetworkSystem.func_151270_a(NetworkSystem.java:105) ~[?:?] {re:classloading}
	at net.minecraft.client.Minecraft.loadWorld(Minecraft.java:1790) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:randompatches.mixins.json:client.MinecraftMixin,pl:mixin:APP:mining_helmet.mixins.json:MinecraftMixin,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:outer_end.mixins.json:BackgroundMusicMixin,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:notenoughcrashes.mixins.json:client.MixinMinecraftClient,pl:mixin:APP:abnormals_core.mixins.json:client.MinecraftMixin,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorMinecraft,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_238192_a_(Minecraft.java:1685) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:randompatches.mixins.json:client.MinecraftMixin,pl:mixin:APP:mining_helmet.mixins.json:MinecraftMixin,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:outer_end.mixins.json:BackgroundMusicMixin,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:notenoughcrashes.mixins.json:client.MixinMinecraftClient,pl:mixin:APP:abnormals_core.mixins.json:client.MinecraftMixin,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorMinecraft,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screen.CreateWorldScreen.func_195352_j(CreateWorldScreen.java:260) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screen.CreateWorldScreen.lambda$init$11(CreateWorldScreen.java:205) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.widget.button.Button.func_230930_b_(SourceFile:33) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.gui.widget.button.AbstractButton.func_230982_a_(SourceFile:16) ~[?:?] {re:mixin,re:classloading}
	at net.minecraft.client.gui.widget.Widget.func_231044_a_(Widget.java:136) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.INestedGuiEventHandler.func_231044_a_(SourceFile:27) ~[?:?] {re:computing_frames,re:mixin,re:classloading}
	at net.minecraft.client.MouseHelper.func_198033_b(MouseHelper.java:87) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:randompatches.mixins.json:client.keybindings.MouseHelperMixin,pl:mixin:APP:ftbchunks-common.mixins.json:MouseHandlerMixin,pl:mixin:APP:mixins.modernui-forge.json:MixinMouseHandler,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screen.Screen.func_231153_a_(Screen.java:427) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:gamemenumodoption.mixins.json:ScreenMixin,pl:mixin:APP:quark.mixins.json:client.ScreenMixin,pl:mixin:APP:mixins.modernui-forge.json:MixinScreen,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper.func_198023_a(MouseHelper.java:85) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:randompatches.mixins.json:client.keybindings.MouseHelperMixin,pl:mixin:APP:ftbchunks-common.mixins.json:MouseHandlerMixin,pl:mixin:APP:mixins.modernui-forge.json:MixinMouseHandler,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper.func_228030_c_(MouseHelper.java:181) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:randompatches.mixins.json:client.keybindings.MouseHelperMixin,pl:mixin:APP:ftbchunks-common.mixins.json:MouseHandlerMixin,pl:mixin:APP:mixins.modernui-forge.json:MixinMouseHandler,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.execute(SourceFile:94) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.MouseHelper.func_228028_b_(MouseHelper.java:180) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:randompatches.mixins.json:client.keybindings.MouseHelperMixin,pl:mixin:APP:ftbchunks-common.mixins.json:MouseHandlerMixin,pl:mixin:APP:mixins.modernui-forge.json:MixinMouseHandler,pl:mixin:A,pl:runtimedistcleaner:A}
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36) ~[lwjgl-glfw-3.2.2.jar:build 10] {}
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.2.2.jar:build 10] {}
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3174) ~[lwjgl-glfw-3.2.2.jar:build 10] {}
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(SourceFile:127) ~[?:?] {re:mixin,re:classloading}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:999) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:randompatches.mixins.json:client.MinecraftMixin,pl:mixin:APP:mining_helmet.mixins.json:MinecraftMixin,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:outer_end.mixins.json:BackgroundMusicMixin,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:notenoughcrashes.mixins.json:client.MixinMinecraftClient,pl:mixin:APP:abnormals_core.mixins.json:client.MinecraftMixin,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorMinecraft,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:randompatches.mixins.json:client.MinecraftMixin,pl:mixin:APP:mining_helmet.mixins.json:MinecraftMixin,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:outer_end.mixins.json:BackgroundMusicMixin,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:notenoughcrashes.mixins.json:client.MixinMinecraftClient,pl:mixin:APP:abnormals_core.mixins.json:client.MinecraftMixin,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorMinecraft,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) ~[1.16.5.jar:?] {re:classloading,xf:fml:screenshotclipboard:coremodone,re:mixin,xf:fml:screenshotclipboard:coremodone,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {re:classloading}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?] {re:classloading}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {re:classloading}
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.16.5-36.2.8.jar:36.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {re:classloading}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {re:classloading}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {re:classloading}
Caused by: io.netty.channel.ChannelException: failed to open a new selector
	at io.netty.channel.nio.NioEventLoop.openSelector(NioEventLoop.java:177) ~[netty-all-4.1.25.Final.jar:4.1.25.Final] {}
	at io.netty.channel.nio.NioEventLoop.<init>(NioEventLoop.java:151) ~[netty-all-4.1.25.Final.jar:4.1.25.Final] {}
	at io.netty.channel.nio.NioEventLoopGroup.newChild(NioEventLoopGroup.java:127) ~[netty-all-4.1.25.Final.jar:4.1.25.Final] {}
	at io.netty.channel.nio.NioEventLoopGroup.newChild(NioEventLoopGroup.java:36) ~[netty-all-4.1.25.Final.jar:4.1.25.Final] {}
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:84) ~[netty-all-4.1.25.Final.jar:4.1.25.Final] {}
	... 40 more
Caused by: java.io.IOException: Unable to establish loopback connection
	at sun.nio.ch.PipeImpl$Initializer.run(PipeImpl.java:94) ~[?:?] {}
	at sun.nio.ch.PipeImpl$Initializer.run(PipeImpl.java:61) ~[?:?] {}
	at java.security.AccessController.doPrivileged(Native Method) ~[?:?] {}
	at sun.nio.ch.PipeImpl.<init>(PipeImpl.java:171) ~[?:?] {}
	at sun.nio.ch.SelectorProviderImpl.openPipe(SelectorProviderImpl.java:50) ~[?:?] {}
	at java.nio.channels.Pipe.open(Pipe.java:155) ~[?:?] {}
	at sun.nio.ch.WindowsSelectorImpl.<init>(WindowsSelectorImpl.java:142) ~[?:?] {}
	at sun.nio.ch.WindowsSelectorProvider.openSelector(WindowsSelectorProvider.java:44) ~[?:?] {}
	at io.netty.channel.nio.NioEventLoop.openSelector(NioEventLoop.java:175) ~[netty-all-4.1.25.Final.jar:4.1.25.Final] {}
	at io.netty.channel.nio.NioEventLoop.<init>(NioEventLoop.java:151) ~[netty-all-4.1.25.Final.jar:4.1.25.Final] {}
	at io.netty.channel.nio.NioEventLoopGroup.newChild(NioEventLoopGroup.java:127) ~[netty-all-4.1.25.Final.jar:4.1.25.Final] {}
	at io.netty.channel.nio.NioEventLoopGroup.newChild(NioEventLoopGroup.java:36) ~[netty-all-4.1.25.Final.jar:4.1.25.Final] {}
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:84) ~[netty-all-4.1.25.Final.jar:4.1.25.Final] {}
	... 40 more
Caused by: java.net.BindException: Cannot assign requested address: connect
	at sun.nio.ch.Net.connect0(Native Method) ~[?:?] {}
	at sun.nio.ch.Net.connect(Net.java:476) ~[?:?] {}
	at sun.nio.ch.Net.connect(Net.java:468) ~[?:?] {}
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:692) ~[?:?] {}
	at java.nio.channels.SocketChannel.open(SocketChannel.java:194) ~[?:?] {}
	at sun.nio.ch.PipeImpl$Initializer$LoopbackConnector.run(PipeImpl.java:127) ~[?:?] {}
	at sun.nio.ch.PipeImpl$Initializer.run(PipeImpl.java:76) ~[?:?] {}
	at sun.nio.ch.PipeImpl$Initializer.run(PipeImpl.java:61) ~[?:?] {}
	at java.security.AccessController.doPrivileged(Native Method) ~[?:?] {}
	at sun.nio.ch.PipeImpl.<init>(PipeImpl.java:171) ~[?:?] {}
	at sun.nio.ch.SelectorProviderImpl.openPipe(SelectorProviderImpl.java:50) ~[?:?] {}
	at java.nio.channels.Pipe.open(Pipe.java:155) ~[?:?] {}
	at sun.nio.ch.WindowsSelectorImpl.<init>(WindowsSelectorImpl.java:142) ~[?:?] {}
	at sun.nio.ch.WindowsSelectorProvider.openSelector(WindowsSelectorProvider.java:44) ~[?:?] {}
	at io.netty.channel.nio.NioEventLoop.openSelector(NioEventLoop.java:175) ~[netty-all-4.1.25.Final.jar:4.1.25.Final] {}
	at io.netty.channel.nio.NioEventLoop.<init>(NioEventLoop.java:151) ~[netty-all-4.1.25.Final.jar:4.1.25.Final] {}
	at io.netty.channel.nio.NioEventLoopGroup.newChild(NioEventLoopGroup.java:127) ~[netty-all-4.1.25.Final.jar:4.1.25.Final] {}
	at io.netty.channel.nio.NioEventLoopGroup.newChild(NioEventLoopGroup.java:36) ~[netty-all-4.1.25.Final.jar:4.1.25.Final] {}
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:84) ~[netty-all-4.1.25.Final.jar:4.1.25.Final] {}
	... 40 more

back to the version 1.1.2 it works well.

**Comment by yuesha-yc** [comment]
What other mods do you install? I cannot replicate this issue.

**Comment by magcicada** [comment]
I uninstall the McAfee and it works well, thanks.
